name: Deploy Java app to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: araba-sharingbook
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}
  JAVA_VERSION: 17
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Action
        uses: actions/checkout@v2

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: maven build, clean
        run: |
          mvn clean package -DskipTests

      # - name: Login via Azure CLI
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          # azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
          # action: Deploy
          publish-profile: ${{ env.AZURE_CREDENTIALS }}
          # use-staging-deployment: false
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.jar'

        # with:
        #   azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
        #   action: Deploy
        #   service-name: blog
        #   app-name: blog
        #   use-staging-deployment: false
        #   package: ${{ env.ASC_PACKAGE_PATH }}/target/*.jar
